### ISSUE TITLE
relative import of images

### ISSUE THREAD

**Issue by DJOCKER-FACE** [Princesseuh/astro-eleventy-img#6]
I don't know if I'm getting this wrong but it's not possible to run this in production, I'm trying to run it as a node middleware,

```

import { generateImage } from 'astro-eleventy-img';

const myImage = generateImage('src/assets/my_image.png', {
  // The options here are passed directly to eleventy-img
  widths: [300],
  formats: ['webp', 'avif'],
});


<img src={myImage.webp[0].url} />
```

Here in the docs you clearly import the image as a non-relative file path. 
While in Astro docs:
https://docs.astro.build/en/guides/images/#src

They state that it should be imported as a relative path. 

In production when we try to generate the image with a non-relative path the image is not found, resulting in the error:

```
Lone/dist/server/entry.mjs:8512:5) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: './assets/images/Copper1.jpg'
}
```
Couldn't figure out a fix I don't know if I have something wrong! 

ofc running this in dev has no problem since we still have access to src.

**Comment by Princesseuh** [comment]
Hey, 

Just to make sure, this project and the official @astrojs/image integration are not related, so the linked docs is not relevant here 😅

`astro-eleventy-img` was built before SSR was added to Astro, so it probably just doesn't support SSR.

It expect to have access to all the source images at build time, which you probably don't in SSR (unless you move over the images manually / make the path compatible)

**Comment by DJOCKER-FACE** [comment]
Got it maybe we should add that in the docs, so it's not confusing.

**Comment by Princesseuh** [comment]
Updated README with a mention that SSR is not supported
